name: Run df Command

on:
  workflow_dispatch:

jobs:
  run-df:
    runs-on: ubuntu-latest
    steps:
      - name: Run df command
        run: df -h
      - name: Run lsblk command
        run: lsblk
      - name: Run lscpu command
        run: lscpu
  run-df-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Run df command
        run: df -h
      - name: Run lsblk command
        run: lsblk
      - name: Run lscpu command
        run: lscpu
  examine-disk-win:
    runs-on: windows-latest
    steps:
      - name: pwd
        shell: pwsh
        run: pwd
      - name: check disks
        shell: pwsh
        run: |
          Get-CimInstance -ClassName Win32_LogicalDisk |
            Select-Object -Property DeviceID, VolumeName, FileSystem,
              @{Name='SizeGB';Expression={[math]::Round($_.Size/1GB,2)}},
              @{Name='FreeGB';Expression={[math]::Round($_.FreeSpace/1GB,2)}} |
            Format-Table -AutoSize
